### PR TITLE
Fixes #25 Fix docs script

### LINKED ISSUE #25: Write script to move autogenerated sidebar content to API.widgets from the Interfaces tab
When you run `npm run docs`, TypeDoc automatically created a new "Interfaces" key in the sidebar. 
As a solution to this issue, we would need to write a script to move contents from here to the "Api" section.

### PR DESCRIPTION
**Pull request by michaeltintiuc**
Fixes #25 
Create a new script that handles all things docs related:
- Used node's `rmdirSync` instead of `rm -rf` in order to have better cross-platform support
- Move the generated array from `guides.Interfaces` to `api.Interfaces`
- Delete `api.Widgets` array

### CODE REVIEW

File: scripts/docs.js [hunk 1]
```diff
@@ -0,0 +1,38 @@
...
+    fs.unlinkSync(`${API_PATH}/${fileName}`);
+  }
+});
+
+if (sidebarsData.guides && sidebarsData.guides.Interfaces) {
+  const interfaces = sidebarsData.guides.Interfaces;
+  delete sidebarsData.guides.Interfaces;
+
+  if (sidebarsData.api) {
+    sidebarsData.api.Interfaces = interfaces;
```
Comment (shubhamzanwar) [inline scripts/docs.js:19]: all looks good. Could you just change this to `sidebarsData.api.Widgets = interfaces`?
We want the heading to be "Widgets"

**Review by shubhamzanwar — APPROVED** [review]

**Comment by shubhamzanwar** [comment]
Thanks for this 🚀

**Comment by shubhamzanwar** [comment]
@all-contributors please add @michaeltintiuc for Infrastructure
